### ISSUE TITLE
Where can the AppImage be downloaded?

### ISSUE THREAD

**Issue by probonopd** [BobyMCbobs/simplechroot#1]
https://github.com/BobyMCbobs/simplechroot/blob/faa303efbb90d4a3f19feb47a00a099acaa23a24/.gitignore#L5

Best would be on https://github.com/BobyMCbobs/simplechroot/releases.

**Comment by BobyMCbobs** [comment]
GitHub is my code mirror from GitLab, I'd stash them there but I don't think you can.
I'll make a release and put it there.

**Comment by BobyMCbobs** [comment]
I've added the AppImage to the release page.

**Comment by probonopd** [comment]
Is this a command line application? In this case, it needs `Terminal=true` in the desktop file. Thanks.

**Comment by BobyMCbobs** [comment]
Good point. Forgot about that.

I've fixed that and re-released it.
